Solutions for issue #26
sherbold/autorank pull request #27
Opened 2024-05-07 23:48 UTC by msotocalvo

Here's a simple implementation of some customization features that allows the user to modified visual parameters of the CD. Regards

2024-05-10 07:49 UTC, msotocalvo commented
Sorry, seems like I created the PR over an old fork I created before. Could you please check the updated PR? In this version I also included the possibility to customize the labels of the populations. Regards

2024-06-17 07:20 UTC, sherbold requested changes
Looks in general good, but there are some aspects that break existing behavior, docstrings are missing, and I think some code from local modifactions for storing an excel file is also still in there

2024-06-17 07:20 UTC, sherbold commented on autorank/_util.py
> +    ax.set_title(title, fontsize=fontsize + 15)
needs None check, so that no title is added if no title is passed as argument

2024-06-17 07:20 UTC, sherbold commented on autorank/_util.py
> +    # Export to Excel
this seems to be local code

2024-06-17 07:20 UTC, sherbold commented on autorank/_util.py
> -        for j in range(i+1, len(reordered_data.columns)):
What are these changes? Are they only for the excel-export?

2024-07-31 08:49 UTC, sherbold commented
@msotocalvo I am planning a release for mid/end of August to incorporate the latest small changes and fixed. I would love to include this is well, if the remaining issues are resolved.

2024-07-31 08:56 UTC, msotocalvo commented
Dear Steffen,

Thank you for considering my suggestions. I have been quite busy but I will
work to solve your previous comments during next week.

Best regards

El El mié, 31 jul 2024 a la(s) 17:50, Steffen Herbold <
***@***.***> escribió:

> @msotocalvo <https://github.com/msotocalvo> I am planning a release for
> mid/end of August to incorporate the latest small changes and fixed. I
> would love to include this is well, if the remaining issues are resolved.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sherbold/autorank/pull/27#issuecomment-2259990368>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7PLFLKCDALCPFR2NY7FZUTZPCQMFAVCNFSM6AAAAABHL5IEJGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENJZHE4TAMZWHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-08 06:55 UTC, closed without merging